version: '3'
services:
  hub:
    image: selenium/hub:4.32
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chromium:4.32
    shm_size: '2g'
    deploy:
      replicas: 4
    depends_on:
      - hub
    env_file: .env
  firefox:
    image: selenium/node-firefox:4.32
    shm_size: '2g'
    deploy:
      replicas: 4
    depends_on:
      - hub
    env_file: .env